/* Generated By:JavaCC: Do not edit this line. BaccoConstants.java */
package Bacco;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BaccoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TEXTO = 11;
  /** RegularExpression Id. */
  int TIPO_DECIMAL = 12;
  /** RegularExpression Id. */
  int TIPO_INTEGRAL = 13;
  /** RegularExpression Id. */
  int READ = 14;
  /** RegularExpression Id. */
  int PRINT = 15;
  /** RegularExpression Id. */
  int START = 16;
  /** RegularExpression Id. */
  int ATTR = 17;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 18;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 19;
  /** RegularExpression Id. */
  int ABRE_CHAVE = 20;
  /** RegularExpression Id. */
  int FECHA_CHAVE = 21;
  /** RegularExpression Id. */
  int SOMA = 22;
  /** RegularExpression Id. */
  int SUB = 23;
  /** RegularExpression Id. */
  int DIVISAO = 24;
  /** RegularExpression Id. */
  int MULTI = 25;
  /** RegularExpression Id. */
  int POTENCIA = 26;
  /** RegularExpression Id. */
  int IF = 27;
  /** RegularExpression Id. */
  int ELSE = 28;
  /** RegularExpression Id. */
  int TIPO_TEXTO = 29;
  /** RegularExpression Id. */
  int TIPO_NUMERICO = 30;
  /** RegularExpression Id. */
  int ID = 31;
  /** RegularExpression Id. */
  int RELACAO = 32;
  /** RegularExpression Id. */
  int AND = 33;
  /** RegularExpression Id. */
  int OR = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int CONCATENAR = 36;
  /** RegularExpression Id. */
  int VIRGULA = 37;
  /** RegularExpression Id. */
  int END = 38;
  /** RegularExpression Id. */
  int FIM_DA_LINHA = 39;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comentario_linha = 1;
  /** Lexical state. */
  int comentario = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"@\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\":--\"",
    "\"--:\"",
    "<token of kind 10>",
    "<TEXTO>",
    "<TIPO_DECIMAL>",
    "<TIPO_INTEGRAL>",
    "\"read\"",
    "\"print\"",
    "\"Start\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"^\"",
    "\"IsTrue\"",
    "\"IsNot\"",
    "\"text\"",
    "\"number\"",
    "<ID>",
    "<RELACAO>",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"#\"",
    "\",\"",
    "\"End\"",
    "\";\"",
  };

}
